# -*- coding: utf-8 -*-
"""
/***************************************************************************
 vp_freifleaschen
                                 A QGIS plugin
 Ermöglicht es dem Benutzer, eine Linie zu erstellen und Auswirkungen zu bewerten
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-10
        copyright            : (C) 2024 by Valon Sinani
        email                : valonsinani89@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load vp_freifleaschen class from file vp_freifleaschen.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .vp_freifleaschen_plugin import vp_freifleaschen
    return vp_freifleaschen(iface)
